### ISSUE TITLE
Add tests based on current issues

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/kompose#205] opened 2016-10-12 17:29 UTC
That fail due to libcompose v2 support...

Add wiki page and keep track of tests.

**Comment by ericchiang** [comment] 2016-10-30 17:35
kompose could definitely use more unit test. I only see two on HEAD.

I've seen a ton of PRs be merged without unit tests. Most of the work of adding new features is proper testing to prevent regressions and help reviewers have confidence in changes. It might be a reasonable idea to start enforcing tests as part of PRs as well.

```
$ go test -race -cover -v $( go list github.com/kubernetes-incubator/kompose/... | grep -v '/vendor/' )
?   	github.com/kubernetes-incubator/kompose	[no test files]
=== RUN   TestParseVolume
--- PASS: TestParseVolume (0.00s)
PASS
coverage: 0.0% of statements
ok  	github.com/kubernetes-incubator/kompose/cli/app	1.128s	coverage: 0.0% of statements
?   	github.com/kubernetes-incubator/kompose/cli/command	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/kobject	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/loader	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/loader/bundle	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/loader/compose	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/transformer	[no test files]
=== RUN   TestKomposeConvert
--- PASS: TestKomposeConvert (0.00s)
	kubernetes_test.go:215: Test case: Convert to Deployments (D)
	kubernetes_test.go:215: Test case: Convert to DaemonSets (DS)
	kubernetes_test.go:215: Test case: Convert to ReplicationController (RC)
	kubernetes_test.go:215: Test case: Convert to D, DS, and RC
PASS
coverage: 40.5% of statements
ok  	github.com/kubernetes-incubator/kompose/pkg/transformer/kubernetes	1.095s	coverage: 40.5% of statements
?   	github.com/kubernetes-incubator/kompose/pkg/transformer/openshift	[no test files]
?   	github.com/kubernetes-incubator/kompose/version	[no test files]
```

**Comment by cdrage** [comment] 2016-10-31 18:58
@ericchiang That looks like a way better command to use to add to unit tests, perhaps we add this to the current `make test-unit` command we have?

**Comment by surajssd** [comment] 2017-03-27 09:15
i think we are doing good on this, so closing it. Thanks @surajnarwade for bringing this to my notice!

**Closed by surajssd** 2017-03-27 09:15 UTC
Labels: kind/testing
