### ISSUE TITLE
no commit hash in kompose 0.3.0 version information

### ISSUE THREAD

**Issue by dustymabe** [kubernetes-incubator/kompose#487] opened 2017-03-13 00:10 UTC
[link-to-rpm](https://kojipkgs.fedoraproject.org//packages/kompose/0.3.0/0.1.git135165b.fc25/x86_64/kompose-0.3.0-0.1.git135165b.fc25.x86_64.rpm)

For last release I saw:
```
$ kompose --version
kompose version 0.1.2 (92ea047)
```

With newer rpm I see:
```
[vagrant@f25vanilla ~]$ kompose version
0.3.0 (HEAD)
```

also the move from `kompose --version` to `kompose version` is odd. We should probably support `--version` as well, if possible.

```
[vagrant@f25vanilla ~]$ kompose --version
Error: unknown flag: --version
...
```

**Comment by cdrage** [comment] 2017-03-13 15:04
@dustymabe 

We moved to `kompose version` instead of `kompose --version` in order to familiarize those who have used `kubectl` or `oc`. Since development usually overlaps between all three, we found that having similar commands help!

Yup, the has was my fault. I added that manually last version when it should of been just (HEAD).  See #411

**Comment by cdrage** [comment] 2017-03-13 15:06
We need to have a discussion about including git hash in the version as per #422 ... I like having a commit ID within it, but the problem is when people `go get` it, it'll appear as the git commit hard-coded in when in reality it's the latest dev branch.

**Comment by dustymabe** [comment] 2017-03-13 15:07
hmm. what I'm saying is that I prefer the more verbose output. I wish it was:

```
[vagrant@f25vanilla ~]$ kompose version
0.3.0 (aaabbbc)
```

**Comment by dustymabe** [comment] 2017-03-13 15:07
if this can't be achieved, that is ok

**Comment by kadel** [comment] 2017-03-15 11:49
It can be achieved, but it has to be build from source cloned from git with proper [ldflags](https://github.com/kubernetes-incubator/kompose/blob/master/Makefile#L18) or using `make build`

**Comment by surajssd** [comment] 2017-05-18 14:04
I think this is solved so closing it!

**Closed by surajssd** 2017-05-18 14:04 UTC
Labels: priority/P3
